version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/step3/zip/
    #overwrite: yes 아래로 변경
    file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: stop.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: start.sh #codedeploy_deploy.sh
      timeout: 60
      runas: ubuntu
  ValidateService:
    - location: health.sh
      timeout: 60
      runas: ubuntu

